//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITLab.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Computers()
        {
            this.CPUs = new HashSet<CPUs>();
            this.GPUs = new HashSet<GPUs>();
        }
    
        public int ID { get; set; }
        public string TypeComputer { get; set; }
        public string SizeRAM { get; set; }
        public string TypeRAM { get; set; }
        public Nullable<int> SizeHardDisk { get; set; }
        public string TypeHardDisk { get; set; }
        public Nullable<System.DateTime> TimeOfOrder { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CPUs> CPUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPUs> GPUs { get; set; }
    }
}
