//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITLab.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPUs
    {
        public int ID { get; set; }
        public string Frequency { get; set; }
        public string Series { get; set; }
        public string Model { get; set; }
        public Nullable<int> CacheSize { get; set; }
        public Nullable<int> NumberOfCores { get; set; }
        public Nullable<int> ComputerId { get; set; }
    
        public virtual Computers Computers { get; set; }
    }
}
